### ISSUE TITLE
Celshade driver - Volumetric Light not working anymore

### ISSUE THREAD

**Issue by onelsonic** [armory3d/driver_celshade#14]
The Celshade example is not working anymore, it crashs with no error in Krom and returns the error below in HTML5.
This error disappears when you disable the **"Volumetric Light"**

```
Failed to load resource: net::ERR_FILE_NOT_FOUND
kha.js:1 Sources/iron/data/Data.hx:471: {
	url : blue_noise64.png, 
	error : [object Event]
}
```

I guess some changes were made to the Desktop/Mobile renderers that need to be replicated into the Celshade renderer.
Here is the file example that has been simplified : 
https://github.com/onelsonic/armory_tests/blob/master/forest3.7z?raw=true

<img width="205" alt="2021-06-04 18_29_05-Blender  C__Users_devWin10_Downloads_forest3_forest3 blend" src="https://user-images.githubusercontent.com/53947594/120834026-c6572980-c562-11eb-8478-0332f337164c.png">

**Comment by MoritzBrueckner** [comment]
It seems that the same happens everytime some embedded asset is required, like this:

```python
assets.add_embedded_data('blue_noise64.png')
```

So it also happens when you enable SMAA or TAA for example. I suspect that this is no issue of the celshade driver but instead some issue with how assets are (now?) handled in Armory, it could be some order-of-operations issue.

**Comment by luboslenco** [comment]
Pushed a fix at https://github.com/armory3d/driver_celshade/commit/119f847f719568aae62ec6d37026cea4521047f4.

**Comment by onelsonic** [comment]
I confirmed that it works thanks
