### ISSUE TITLE
BUG: Implemented receive shadow prop

### ISSUE THREAD

**Issue by onelsonic** [armory3d/driver_celshade#7]
The receive shadow parameter is not working properly.
The shadows casted in the scene are not respecting the "Receive Shadow" from a material parameter.
<img width="283" alt="2020-10-09 14_24_32-" src="https://user-images.githubusercontent.com/53947594/95582825-78257100-0a3b-11eb-9843-375f63aef73a.png">
A 3Dmodel with "Receive Shadow" disable will receive the shadows.
Shadows should be bypassed if the parameter "Receive Shadow" is disable for a material.

_This is related to this closed issue : [celshader and shadows #1](https://github.com/armory3d/driver_celshade/issues/1)
shadows fixed at [d017d9a ](https://github.com/armory3d/driver_celshade/commit/d017d9add3fb5eac6ed999845ca0b15871166f9f) (although only sun light is implemented)_

unfortunately emission and receive shadows are still not working properly.

**Comment by onelsonic** [comment]
Hi @MoritzBrueckner great 👍 other light types works but the shadow issues is still remaining.
I just put together an example so we can see it.

komBuild: [buildshadowscelshadetest.7z](https://github.com/onelsonic/armory_tests/raw/master/shadowscelshadetest/buildshadowscelshadetest.7z)
sourcefile: [shadowscelshadetest.7z](https://github.com/onelsonic/armory_tests/raw/master/shadowscelshadetest/shadowscelshadetest.7z)

Using the celshade driver, we can see the background is receiving a shadow even if it material has the "receive shadow" parameter disabled.

Details of the scene:
there is a ground with a cube, a sun, a sunsphere (to locate the sun) and a Big Sphere used as a sky background.
The goal is to remove the shadow from the sky background 
"F" and "G" (qwerty keyboard) to make to sun and sunsphere to rotate
The shadow in the sky should not be displayed.
![Screen Recording 2020-10-31 at 10 09 50 43 PM](https://user-images.githubusercontent.com/53947594/97790089-04076480-1bc6-11eb-9728-15d89f04f45b.gif)

**Comment by MoritzBrueckner** [comment]
Thanks for the files and sorry for my late answer, this week was a bit stressful.

What you see in the file is actually not really a shadow, but instead the toon shading that is applied to the mesh (calculated [here](https://github.com/armory3d/driver_celshade/blob/master/blender.py#L44) and applied [here](https://github.com/armory3d/driver_celshade/blob/master/blender.py#L107)). The actual "receive shadow" setting is working correctly (you can set `dotNL` to 1.0 in the code to test this).

What we could do is to allow the user to set the amount of "darkening" for the shading, what do you think of this? Is there a good name for this attribute? Its value range is [0, 1]. Then, when no darkening is applied, you don't get this shadow-like shading. However, this would be a global setting for now that affects all materials, but it should be possible to change Armory so that you can add per-material custom settings for drivers.

**Comment by onelsonic** [comment]
Hi @MoritzBrueckner thanks for pointing it out,
To control the rendering of a good NPR scene, we need to control the shading for each models.

I can see 4 possible ways to correct it in Armory but I am not sure of the internals of the renderer:

_**1st possible solution:**_ 
___________


trying to play with the line you mentioned line106/107 : [here](https://github.com/armory3d/driver_celshade/blob/master/blender.py#L107 )

Maybe there a way to process one 3d object differently than to others so that the shading is not applied to this model?
Or I don't know if the shading is processed at a pixel level like in GLSL and not for each pixel on the screen and not for each 3d objects?

If this can be done, something like:
```
frag.add_out('vec4 fragColor')
if con_mesh.is_elem('sky'):
	frag.write('vec3 direct = basecol * step(0.5, 1.0) * visibility * sunCol;')
else:
	frag.write('vec3 direct = basecol * step(0.5, dotNL) * visibility * sunCol;')

```
is there a way to check if the model name is "sky" or "cube" and if so applied the shading?
using : 
if con_mesh.is_elem('sky') 
is not working


_**2nd possible solution:**_ 
___________
Maybe we can use a custom material to overwrite the behavior of the celshade renderer for one specific model?
something like : 
<img width="290" alt="2020-11-13 19_41_58-Blender_  C__Users_devWin10_Desktop_seed2_seed_bfirst1 blend" src="https://user-images.githubusercontent.com/53947594/99109561-5181c980-25e9-11eb-9b1d-beea494046a7.png">
with custom files :
skytest1.frag.glsl
skytest1.vert.glsl

_**3rd possible solution:**_ 
___________
in blender when using the Eevee or Cycles renderer if you want to prevent shadow on a model to be rendered you will use the following trick:
<img width="693" alt="2020-11-13 20_08_29-Blender  C__Users_devWin10_Desktop_GITHUB_GITHUB_armory_tests_shadowscelshadetes" src="https://user-images.githubusercontent.com/53947594/99111265-15039d00-25ec-11eb-8409-5764a209e1cc.png">
Maybe we can use the same so than the celshade renderer can check the emission value in the shader?

_**4th possible solution:**_ 
___________
playing the the model normales and reorient them so that the light is not producing a shadow on the model from any angles.
(issue if that the light path need to be known entirety and even it might not be possible.)
I will try to flip the normales but not sure it will work.

Do you have any insight what solution might be possible to use?

**Comment by onelsonic** [comment]
4th method does not work, the shading gets rotated by a 90 degrees and is still there.

**Comment by MoritzBrueckner** [comment]
It should be doable to implement per-material settings for drivers, that would be the first of your proposed methods.

Instead of having a option to apply shading or not, I would propose the possibility to choose how much toon shading is applied (in a [0, 1] range). How would you name that parameter (are there any naming conventions regarding toon shading)?

Regarding your other ideas:

- Custom materials should work, I don't think that they get special treatment by the driver.
- The Armory render engine is not a raytracer like cycles, so there is no information about the light paths. The light path node is supported, but it just uses some default values (1.0 or 0.0 depending on the output socket).

**Comment by onelsonic** [comment]
Ok, this is to control the shading for each material so I believe it is called : "Light Intensity Control" for a toon shader.

Here is a reputable japanese toon shader plugin used in Animated Movies for Maya/3dsMax,
they call this "Light Intensity Control" :`
[https://www.psoft.co.jp/en/product/pencil/3dsmax/](https://www.psoft.co.jp/en/product/pencil/3dsmax/) (scroll down)

_Light Intensity Control_
_Light intensity can be modified for individual materials, providing more detailed control over highlights and shading._
_______________
Toon Shader Light Intensity Control = TSlic = float value between [0.0, 1.0]
frag.write('vec3 direct = basecol * step(0.5, TSlic) * visibility * sunCol;')
